export const en = {
  ROTATE: "Rotate",
  LEVELS: "Levels",
  DRAG_PIECE: "Drag this piece to the board",
  GOOD_PLACE: "Good place!",
  ERROR_OUT_OF_BOARD: "Piece out of the board",
  ERROR_ENTRANCE: "Can't block the entrance",
  ERROR_EXIT: "Can't block the exit",
  ERROR_CELL_OCCUPIED: "Cell already occupied",
  ERROR_NO_WAY_OUT: "No way out!",
  ERROR_ISOLATED_CELLS: "Can't isolate cells",
  DUNGEON_CREATED: "Dungeon created!",
  SHARE_YOUR_DUNGEON: "Lock a friend in the dungeon and see if he can beat it!",
  SHARE_ON: "Share on...",
};
